title: Oliver Davies
subtitle: Drupal Developer & System Administrator

description: Oliver Davies, Drupal Developer
author: Oliver Davies
email: oliver@oliverdavies.co.uk
gravatar_url: http://www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

twitter: http://twitter.com/opdavies
twitter_name: opdavies
linkedin: http://uk.linkedin.com/in/opdavies
drupalorg: https://www.drupal.org/user/381388
drupalorg_nice: https://www.drupal.org/u/opdavies
github: http://github.com/opdavies
irc: opdavies
lanyrd: http://lanyrd.com/profile/opdavies
joindin: https://joind.in/user/view/27119
ansible_galaxy: https://galaxy.ansible.com/list#/users/14560

bio: >
  <p><a href="/">Oliver Davies</a> is a Drupal Developer and System Administrator based in the UK. He works for the <a href="https://assoc.drupal.org">Drupal Association</a> and also provides freelance consultancy services for Drupal websites and Linux servers.</p>
  
