sculpin:
  permalink: pretty
  ignore:
    - '_examples/*'
    - '**/*.scss'
    - '**/config.rb'
    - '**/Gemfile*'
sculpin_content_types:
  posts:
    permalink: blog/:slug_title/
    taxonomies:
      - tags
  projects:
    permalink: projects/:slug_title/
    taxonomies:
      - tags
    enabled: false
  talks:
    layout: default
    permalink: talks/:year/:month/:day/:slug_title/
    taxonomies:
      - tags
  testimonials:
    permalink: testimonials/:slug_title/
    layout: default
    enabled: false
sculpin_theme:
  theme: opdavies/opdavies
