sculpin:
  permalink: pretty
  ignore:
    - '_examples/*'
    - '**/*.scss'
    - '**/config.rb'
    - '**/Gemfile*'
sculpin_content_types:
  clients:
    permalink: clients/:slug_title/
    enabled: false
  posts:
    permalink: blog/:slug_title/
    taxonomies:
      - tags
  projects:
    permalink: projects/:slug_title/
    taxonomies:
      - tags
    enabled: false
  talks:
    permalink: talks/:slug_title/
    enabled: false
  testimonials:
    permalink: testimonials/:slug_title/
    enabled: false
sculpin_theme:
  theme: opdavies/opdavies
