title: Oliver Davies
subtitle: Drupal & Linux Specialist
description: Personal website and blog of Oliver Davies, a Drupal Developer and Systems Administrator based in the UK.
url: http://localhost:8000
