title: Oliver Davies
subtitle: Drupal & Linux Specialist
url: http://localhost:8000

elsewhere:
  twitter: http://twitter.com/opdavies
  linkedin: http://uk.linkedin.com/in/opdavies
  drupalorg: https://www.drupal.org/user/381388
  github: http://github.com/opdavies
  irc: opdavies