title: Oliver Davies
subtitle: Drupal & Linux Specialist
description: Oliver Davies, Drupal Developer
url: http://localhost:8000

twitter: http://twitter.com/opdavies
twitter_name: opdavies
linkedin: http://uk.linkedin.com/in/opdavies
drupalorg: https://www.drupal.org/user/381388
drupalorg_nice: https://www.drupal.org/u/opdavies
github: http://github.com/opdavies
irc: opdavies