sculpin:
    permalink: pretty
    ignore:
        - '**/*.scss'
        - '**/config.rb'
        - '**/Gemfile*'

sculpin_content_types:
    posts:
        permalink: blog/:slug_title/
        taxonomies:
            - tags
