title: Oliver Davies
subtitle: Drupal Developer & System Administrator
description: Oliver Davies, Drupal Developer
author: Oliver Davies
email: oliver@oliverdavies.co.uk
gravatar_url: http://www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

# Social links.
twitter: http://twitter.com/opdavies
twitter_name: opdavies
linkedin: http://uk.linkedin.com/in/opdavies
drupalorg: https://www.drupal.org/user/381388
drupalorg_nice: https://www.drupal.org/u/opdavies
github: http://github.com/opdavies
irc: opdavies
lanyrd: http://lanyrd.com/profile/opdavies
joindin: https://joind.in/user/view/27119
ansible_galaxy: https://galaxy.ansible.com/list#/users/14560

bio: >
  <p><a href="/">Oliver Davies</a> is a Drupal Developer and System Administrator based in the UK. He works for the <a href="https://assoc.drupal.org">Drupal Association</a> and also provides freelance consultancy services for Drupal websites and Linux servers.</p>
  
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

main_menu:
  - title: About
    href: /
    class: nav__about
  - title: Work
    href: /work/
    class: nav__work
  - title: Services
    href: /services/
    class: nav__services
  - title: Talks
    href: /talks/
    class: nav__talks
  - title: Blog
    href: /blog/
    class: nav__blog
  - title: Contact
    href: /contact/
    class: nav__contact

meetups:
  - name: SWDUG
    logo: swdug.png
    url: https://swdug.org.uk
  - name: Drupal Bristol
    logo: drupal-bristol.jpeg
    url: https://groups.drupal.org
  - name: PHPSW
    logo: phpsw.jpeg
    url: http://phpsw.uk
  - name: SWLUG
    logo: swlug.png
    url: http://swlug.org.uk
  - name: Accessible Bristol
    logo: accessible-bristol.png
    url: http://www.accessiblebristol.org.uk
