title: Oliver Davies
subtitle: Drupal Developer & System Administrator
description: Oliver Davies, Drupal Developer
url: http://localhost:8000
author: Oliver Davies
email: oliver@oliverdavies.co.uk
gravatar_url: http://www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

twitter: http://twitter.com/opdavies
twitter_name: opdavies
linkedin: http://uk.linkedin.com/in/opdavies
drupalorg: https://www.drupal.org/user/381388
drupalorg_nice: https://www.drupal.org/u/opdavies
github: http://github.com/opdavies
irc: opdavies
lanyrd: http://lanyrd.com/profile/opdavies

bio: >
  <p><a href="/">Oliver Davies</a> is a Drupal Developer and System Administrator based in the UK. He works for the <a href="https://assoc.drupal.org">Drupal Association</a> and also provides freelance consultancy services for Drupal websites and Linux servers.</p>

toolkit:
  - title: Drupal
    url: https://www.drupal.org
  - title: Sculpin
    url: http://sculpin.io
  - title: Git
    url: http://git-scm.com
  - title: SASS
    url: http://sass-lang.com
  - title: Compass
    url: http://compass-style.org
  - title: Susy
    url: http://susy.oddbird.net
  - title: Grunt
    url: http://gruntjs.com
  - title: Vagrant
    url: http://vagrantup.com
  - title: Puppet
    url: http://en.wikipedia.org/wiki/Puppet_%28software%29
  - title: Jenkins
    url: http://jenkins-ci.org